In [1]:
#Importing libraries
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import scipy as sci
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm import tqdm

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import json
data = json.load(open('bitcoin.json'))

In [4]:
data.keys()

dict_keys(['dataset'])

In [5]:
a = pd.DataFrame(pd.Series([x for x in data['dataset']['data']],name='all_data'))

In [6]:
a['Date'] = a['all_data'].map(lambda x: x[0])
a['Open'] = a['all_data'].map(lambda x: x[1])
a['High'] = a['all_data'].map(lambda x: x[2])
a['Low'] = a['all_data'].map(lambda x: x[3])
a['Close'] = a['all_data'].map(lambda x: x[4])
a['Volume_BTC'] = a['all_data'].map(lambda x: x[5])
a['Volume_Currency'] = a['all_data'].map(lambda x: x[6])
a['Weighted Price'] = a['all_data'].map(lambda x: x[7])

In [7]:
del a['all_data']

In [8]:
a['Date'] = pd.to_datetime(a['Date'])

In [9]:
a.head()

,Date,Open,High,Low,Close,Volume_BTC,Volume_Currency,Weighted Price
0,2018-07-08,6755.46,6783.54,6708.97,6745.46,4617.252147,3.112973e+07,6742.047291
1,2018-07-07,6604.74,6820.00,6510.00,6759.99,4842.795871,3.203913e+07,6615.832463
2,2018-07-06,6533.69,6636.15,6449.76,6596.53,5457.672187,3.571456e+07,6543.918537
3,2018-07-05,6575.62,6700.00,6445.31,6533.69,7692.215777,5.062396e+07,6581.193720
4,2018-07-04,6507.99,6792.28,6413.20,6584.25,6706.734006,4.410461e+07,6576.168213

In [10]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2491 entries, 0 to 2490
Data columns (total 8 columns):
Date               2491 non-null datetime64[ns]
Open               2491 non-null float64
High               2491 non-null float64
Low                2491 non-null float64
Close              2491 non-null float64
Volume_BTC         2491 non-null float64
Volume_Currency    2491 non-null float64
Weighted Price     2491 non-null float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 155.8 KB

In [11]:
a = a.sort_values('Date',ascending=True).reset_index(drop=True)

In [12]:
a.head()

,Date,Open,High,Low,Close,Volume_BTC,Volume_Currency,Weighted Price
0,2011-09-13,5.80,6.00,5.65,5.97,58.371382,346.097389,5.929231
1,2011-09-14,5.58,5.72,5.52,5.53,61.145984,341.854813,5.590798
2,2011-09-15,5.12,5.24,5.00,5.13,80.140795,408.259002,5.094272
3,2011-09-16,4.82,4.87,4.80,4.85,39.914007,193.763147,4.854515
4,2011-09-17,4.87,4.87,4.87,4.87,0.300000,1.461000,4.870000

In [13]:
a.shape

(2491, 8)

In [14]:
a['day_1_before'] = 0
a['day_2_before'] = 0
a['day_3_before'] = 0
a['day_4_before'] = 0
a['day_5_before'] = 0
a['day_6_before'] = 0
a['day_7_before'] = 0
a['day_8_before'] = 0
a['day_9_before'] = 0
a['day_10_before'] = 0
a['day_11_before'] = 0
a['day_12_before'] = 0
a['day_13_before'] = 0
a['day_14_before'] = 0

In [15]:
a['day_1_before'][1:] = a['Close'][0:a.shape[0]-1]
a['day_2_before'][2:] = a['Close'][0:a.shape[0]-2]
a['day_3_before'][3:] = a['Close'][0:a.shape[0]-3]
a['day_4_before'][4:] = a['Close'][0:a.shape[0]-4]
a['day_5_before'][5:] = a['Close'][0:a.shape[0]-5]
a['day_6_before'][6:] = a['Close'][0:a.shape[0]-6]
a['day_7_before'][7:] = a['Close'][0:a.shape[0]-7]
a['day_8_before'][8:] = a['Close'][0:a.shape[0]-8]
a['day_9_before'][9:] = a['Close'][0:a.shape[0]-9]
a['day_10_before'][10:] = a['Close'][0:a.shape[0]-10]
a['day_11_before'][11:] = a['Close'][0:a.shape[0]-11]
a['day_12_before'][12:] = a['Close'][0:a.shape[0]-12]
a['day_13_before'][13:] = a['Close'][0:a.shape[0]-13]
a['day_14_before'][14:] = a['Close'][0:a.shape[0]-14]

In [17]:
a['diff'] = a['Close'] - a['day_1_before']

In [19]:
a.tail(3)

,Date,Open,High,Low,Close,Volume_BTC,Volume_Currency,Weighted Price,day_1_before,day_2_before,day_3_before,day_4_before,day_5_before,day_6_before,day_7_before,day_8_before,day_9_before,day_10_before,day_11_before,day_12_before,day_13_before,day_14_before,diff
2488,2018-07-06,6533.69,6636.15,6449.76,6596.53,5457.672187,3.571456e+07,6543.918537,6533.69,6584.25,6507.99,6612.98,6349.99,6385.71,6204.24,5848.33,6135.64,6068.00,6253.61,6153.40,6177.38,6050.45,62.84
2489,2018-07-07,6604.74,6820.00,6510.00,6759.99,4842.795871,3.203913e+07,6615.832463,6596.53,6533.69,6584.25,6507.99,6612.98,6349.99,6385.71,6204.24,5848.33,6135.64,6068.00,6253.61,6153.40,6177.38,163.46
2490,2018-07-08,6755.46,6783.54,6708.97,6745.46,4617.252147,3.112973e+07,6742.047291,6759.99,6596.53,6533.69,6584.25,6507.99,6612.98,6349.99,6385.71,6204.24,5848.33,6135.64,6068.00,6253.61,6153.40,-14.53